---

  - hosts: galaxyserver, slurm, db
    gather_facts: yes
    become: true


    tasks: 
   
      - name: remove any old cvmfs proxy lines if exists
        lineinfile:
          path: /etc/cvmfs/default.local
          state: absent
          regexp: '^CVMFS_HTTP_PROXY'
          backup: yes

      - name: add proxy to cvmfs config
        lineinfile:
          path: /etc/cvmfs/default.local
          line: CVMFS_HTTP_PROXY="{{ cvmfs_proxy }}"
        notify:
          - restart autofs
