---

- name: add options for cvmfs proxy

  block:

    - name: touch cvmfs.local
      file:
        path: /etc/cvmfs/default.local
        state: touch
        mode: '0644'

    - name: remove any old cvmfs proxy lines if exists
      lineinfile:
        path: /etc/cvmfs/default.local
        state: absent
        regexp: '^CVMFS_HTTP_PROXY'
        backup: yes

    - name: add proxy to cvmfs config
      lineinfile:
        path: /etc/cvmfs/default.local
        line: CVMFS_HTTP_PROXY="{{ cvmfs_proxy }}"

    - name: remove any old cvmfs cache lines if exists
      lineinfile:
        path: /etc/cvmfs/default.local
        state: absent
        regexp: '^CVMFS_QUOTA_LIMIT'
        backup: yes
      tags: olaf

    - name: add cache size to cvmfs proxy
      lineinfile:
        path: /etc/cvmfs/default.local
        line: CVMFS_QUOTA_LIMIT="{{ cvmfs_cache_size }}"
      tags: olaf

    - name: create key dir
      file:
        path: /etc/cvmfs/keys/galaxyproject.org
        state: directory
        mode: '0755'

    - name: add pub key
      copy:
        src: cvmfs/data.galaxyproject.org.pub
        dest: /etc/cvmfs/keys/galaxyproject.org/data.galaxyproject.org.pub
        mode: '0644'
        owner: root
        group: root

    - name: add cvmfs to autofs
      command: cvmfs_config setup
      changed_when: false

    - name: dirty permission fix
      file:
        path: /data/part0
        mode: '0777'
        recurse: no
      ignore_errors: True 


#    - name: cvmfs probe
#      command: cvmfs_config probe '{{ item }}'
#      with_items:
#        - "data.galaxyproject.org"
#        - "{{ datausegalaxy }}"
#        - "cvmfs-config.galaxyproject.org"

    - name: enable autofs
      service:
        name: autofs
        state: restarted
        enabled: true


