---

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - squid
    - firewalld

- name: enable and start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - squid
    - firewalld

- name: opening firewall for public
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled 
    immediate: yes
    zone: public
  loop: "{{ public_ports }}"

- name: opening firewall for proxy
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled 
    immediate: yes
    zone: internal
  loop: "{{ proxy_ports }}"

- name: add cvmfs clients to firewall
  firewalld:
    source: "{{ item }}"
    zone: internal
    state: enabled
    permanent: true
    immediate: yes
  loop: "{{ cvmfs_clients }}"
